services:
  app:
    container_name: currencyinfo
    build: .
    ports:
      - '36661:36661'
    depends_on:
      - redis
    networks:
      - app_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGODB_HOST: host.docker.internal
      MONGODB_PORT: 27017

  redis:
    container_name: redis
    image: 'redis:latest'
    networks:
      - app_network

networks:
  app_network:
