services:
  app:
    container_name: currencyinfo
    build: .
    ports:
      - '36661:36661'
    depends_on:
      - redis
    networks:
      - app_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  redis:
    container_name: redis
    image: 'redis:latest'
    networks:
      - app_network

networks:
  app_network:
