services:
  redis:
    container_name: redis
    ports:
      - '6379:6379'
    image: 'redis:latest'
    volumes:
      - redis_data:/data

  mongodb:
    container_name: mongodb
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  mongo_data:
