services:
  app:
    container_name: currencyinfo
    build: .
    restart: always
    ports:
      - '36661:36661'
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./config.jsonc:/usr/src/currencyinfo/config.jsonc
    networks:
      - app_network

  redis:
    container_name: redis
    image: 'redis:latest'
    volumes:
      - redis_data:/data
    networks:
      - app_network

  mongodb:
    container_name: mongodb
    image: 'mongo:latest'
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:

volumes:
  redis_data:
  mongo_data:
